image: node:10.5.0

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

setup:
  stage: setup
  script: ./node_modules/.bin/apidoc -e node_modules/ | npm install

test:
  stage: test
  script: npm test

deploy_staging:
  stage: deploy
  script:
    - ./node_modules/.bin/now

deploy_prod:
  stage: deploy
  script:
    - ./node_modules/.bin/now
    - ./node_modules/.bin/now alias api.dbknews.com
  environment:
    name: production
    url: https://api.dbknews.com
  when: manual
  only:
    - master