image: node:10.5.0

cache:
  paths:
    - node_modules/

stages:
  - setup
  - deploy

setup:
  stage: setup
  script: npm install | ./node_modules/.bin/apidoc -e node_modules/ 

# test:
#   stage: test
#   script: npm test

deploy_staging:
  stage: deploy
  script:
    - ./node_modules/.bin/now --token=NOW_TOKEN

deploy_prod:
  stage: deploy
  script:
    - ./node_modules/.bin/now --token=NOW_TOKEN
    - ./node_modules/.bin/now alias api.dbknews.com --token=NOW_TOKEN
  environment:
    name: production
    url: https://api.dbknews.com
  when: manual
  only:
    - master