image: node:10.5.0

cache:
  paths:
    - node_modules/

stages:
  - setup
  # - test
  - deploy

setup:
  stage: setup
  script: 
    - npm install

# test:
#   stage: test
#   script: npm test

deploy_staging:
  stage: deploy
  script:
    - ./node_modules/.bin/apidoc -e node_modules/ -o doc/
    - ./node_modules/.bin/now --team=the-diamondback-lab --token=$NOW_TOKEN

deploy_prod:
  stage: deploy
  script:
    - ./node_modules/.bin/apidoc -e node_modules/ -o doc/
    - ./node_modules/.bin/now --team=the-diamondback-lab --token=$NOW_TOKEN
    - ./node_modules/.bin/now alias api.dbknews.com --team=the-diamondback-lab --token=$NOW_TOKEN
  environment:
    name: production
    url: https://api.dbknews.com
  when: manual
  only:
    - master